import { NextResponse } from 'next/server';
import path from 'path';
import fs from 'fs';

export async function POST(request) {
  try {
    const { rollNumber, dob } = await request.json();

    if (!rollNumber || !dob) {
      return NextResponse.json({ success: false, message: 'Please provide both Exam Roll Number and Date of Birth' }, { status: 400 });
    }

    // Path to the metadata file generated by our processor script
    const metadataPath = path.join(process.cwd(), 'public', 'admit-cards', 'metadata.json');
    
    if (!fs.existsSync(metadataPath)) {
      return NextResponse.json({ success: false, message: 'Database not initialized. Please run the PDF processor script first.' }, { status: 503 });
    }

    const metadata = JSON.parse(fs.readFileSync(metadataPath, 'utf-8'));
    
    // Format the incoming DOB string into the format "DD Mmm YYYY" (e.g. 16 Jun 2005)
    // Note: if the date is invalid, handled below.
    const dateObj = new Date(dob);
    if (isNaN(dateObj.getTime())) {
      return NextResponse.json({ success: false, message: 'Invalid Date Format.' }, { status: 400 });
    }
    const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
    const formattedDobInput = `${dateObj.getDate().toString().padStart(2, '0')} ${months[dateObj.getMonth()]} ${dateObj.getFullYear()}`;

    const storedDob = metadata[rollNumber];

    if (!storedDob) {
      return NextResponse.json({ success: false, message: 'Admit Card not found for this Exam Roll Number.' }, { status: 404 });
    }

    // Check DOB matches
    if (storedDob.trim().toLowerCase() !== formattedDobInput.toLowerCase()) {
      return NextResponse.json({ success: false, message: 'Invalid Date of Birth for this Exam Roll Number.' }, { status: 401 });
    }

    // If matches, return success and the URL of the PDF
    return NextResponse.json({ 
      success: true, 
      pdfUrl: `/admit-cards/${rollNumber}.pdf` 
    });

  } catch (error) {
    console.error("Admit Card API Error:", error);
    return NextResponse.json({ success: false, message: 'Server error retrieving admit card.' }, { status: 500 });
  }
}
